GET http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3QgVXNlcm5hbWUiLCJpZCI6IjYwNTc2MmQ3OGRkZTUxMjc0YzUxNDhhOCIsImlhdCI6MTYxNjM0Nzk3MCwiZXhwIjoxNjE2MzUxNTcwfQ.xEuZfO76mRXTU-8mGZru5eHczdIY9z7qXhQqHv-PlFI