GET http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3QgVXNlcm5hbWUiLCJpZCI6IjYwNTc2MmQ3OGRkZTUxMjc0YzUxNDhhOCIsImlhdCI6MTYxNjM0NjE2OCwiZXhwIjoxNjE2MzQ5NzY4fQ.QCSjiybzuMTn3RjmVgyHMBzpk65jnah0mPgUx1pFhkw